server:
  port: 8089
srv:
  server1: 8051
  server2: 8052
  server3: 8053

---
spring:
  profiles: zuul
  application:
    name: ${spring.profiles}
zuul:
    ignored-services: '*'
    routes:
        verb:
            path: /


eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://eureka-srv2:${srv.server2}/eureka,http://eureka-srv3:${srv.server3}/eureka,http://eureka-srv1:${srv.server1}/eureka
    register-with-eureka: true
    fetch-registry: true
    should-unregister-on-shutdown: true