server:
  port: 3000


---
spring:
  profiles: locahost
  application:
    name: oauth2ldap
    
security:
  signing-key: MaYzkSjmkzPC57L
  token:
    expiry-time: 180000
    check-token-url: http://localhost:8080/ouath/check_token
  jwt:
    resource-ids: testjwtresourceid
    client-id: testjwtclientid
    client-secret: XY7kmzoNzl100
    grant-type: password
    scope-read: read
    scope-write: write
  encoding-strength: 256
  security-realm: test

  #debug=true
  #endpoints.trace.sensitive=false
  #remove, just for testing
  #spring.ldap.embedded.port=8389
  #spring.ldap.embedded.ldif=classpath:test-server.ldif
  #spring.ldap.embedded.base-dn=dc=mycompany,dc=local
  #spring.datasource.url=jdbc:mysql://localhost/spring
  #spring.datasource.username=root
  #spring.datasource.password=199526
adVdf:
  URL: ldap://10.74.100.16:389
  domain: vodafone.com
  searchFilter: *
  searchBase: DC=internal,DC=vodafone,DC=com
